from spade_label_tool.events.buttons import event_handler as handle_buttons
from spade_label_tool.events.pickers import handle_pickers
from spade_label_tool.events.mouse import handle_mouse
from spade_label_tool.events.keyboards import handle_keyboard
from spade_label_tool.events.confirmations import handle_confirmations
